redhat-best-practices-for-k8s/oct

Dockerfile
Dockerfile.local

https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
Similar changes:
- https://github.com/test-network-function/cnfcert-tests-verification/pull/132
- https://github.com/test-network-function/test-network-function-claim/pull/62
- https://github.com/test-network-function/l2discovery/pull/15
- https://github.com/test-network-function/privileged-daemonset/pull/7
- https://github.com/test-network-function/cnf-certification-test/pull/492

Update Go to 1.18.6

---

.golangci.yml
cmd/tnf/fetch/fetch.go

- Cherry-picked: https://github.com/test-network-function/cnf-certification-test/pull/485
- Linter rules file copied from TNF repo.

Cherry-picking last changes from TNF repo.

---

Dockerfile
Dockerfile.local
go.mod

https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
Related to: https://github.com/test-network-function/cnf-certification-test/pull/531

Upgrade Go to v1.19.1

---

.github/dependabot.yml

Copied from the main `cnf-certification-test` repo to provide dependency updates.

Add dependabot YAML

---

.github/workflows/recreate-image.yml

Quays' robot user and token have already been updated in github's oct repo.

Changed quay account for image pushing.

---

Dockerfile
Dockerfile.local

https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU

Update Go to v1.19.4

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

https://groups.google.com/g/golang-announce/c/wrmRT7JlevE
Related to: https://github.com/test-network-function/cnf-certification-test/pull/779

Update Go to v1.19.5

---

.golangci.yml
Makefile

Related to: https://github.com/test-network-function/cnf-certification-test/pull/863

Update GolangCI-lint to v1.51.1

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local
ROADMAP.md

Related to: https://github.com/test-network-function/cnf-certification-test/pull/864
https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E

Update Go to 1.19.6

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/924

Update Go to 1.20.2

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/994

Update Go to v1.20.3

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1078

Update Go to v1.20.4

---

.golangci.yml
Makefile

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1156

Update GolangCI to v1.53.2

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1165

Update Go to v1.20.5

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1242

Update Go to v1.20.6

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1315

Update Go to v1.20.7

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1387

Update Go to v1.21.1

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1504

Update Go to v1.21.2

---

.github/workflows/pre-main.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1558

Update Go to v1.21.3

---

.github/workflows/preflight.yml

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1569

Run preflight against latest image

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1598

Update Go to v1.21.4

---

pkg/certdb/onlinecheck/onlinecheck.go

Verifed with the OpenShift Elasticsearch Operator (only present in the catalog Red Hat Operators).

operator: add redhat-operators organizacion check in the catalog

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1697

Update Go to v1.21.5

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1804

Update Go to v1.21.6

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1873

Update Go to v1.21.7

---

.golangci.yml
Makefile

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1892

Update GolangCI-lint to v1.56.2

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1902

Update Go to v1.22

---

Dockerfile
Dockerfile.local

Follow up to: #100 
Forgot to adjust the Golang versions in the Dockerfiles.

Adjust Dockerfiles for multi-arch

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1973

Update Go to v1.22.2

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2053

Update Go to v1.22.3

---

.golangci.yml
Makefile

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2054

Update GolangCI-lint to v1.58.1

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
.github/workflows/recreate-image.yml

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2079 

Update ubuntu to 24.04

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
.github/workflows/recreate-image.yml
.github/workflows/scorecard.yml

Related to:
- https://github.com/test-network-function/cnf-certification-test/pull/2112
- https://github.com/test-network-function/cnf-certification-test-partner/pull/440
- https://github.com/test-network-function/cnfcert-tests-verification/pull/785

Revert ubuntu-24.04 due to cancelled action runs

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2134

Update Go to v1.22.4

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2229

Update Go to v1.22.5

---

.github/workflows/preflight.yml
.github/workflows/recreate-image.yml
README.md

Update image tag to new org

---

.github/workflows/recreate-image.yml

Split the build into two separate jobs.

Split legacy and normal YAML

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2360

Update Go to v1.22.6

---

.golangci.yml
Makefile
cmd/tnf/fetch/fetch.go

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2372

Update GolangCI-lint to v1.60.3

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2402

Update Go to v1.23.1

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2482

Update Go to v1.23.2

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2609

Update Go to v1.23.4

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2704

Update Go to v1.23.5

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2766

Update Go to v1.23.6

---

Makefile

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2793

Update GolangCI to v1.64.3

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
Dockerfile
Dockerfile.local
Makefile
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2795

Update Go to v1.24.0

---

.golangci.yml

Testing to see if this passes the linter.

Fix the golangci-lint errors

---

Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2855

Update Go to v1.24.1

---

.github/workflows/preflight.yml
.github/workflows/recreate-image.yml

Prevent forks from running crons:
Similar to: 
- https://github.com/redhat-best-practices-for-k8s/certsuite-overview/pull/36
- https://github.com/openshift-kni/eco-goinfra/pull/961
- https://github.com/openshift-kni/eco-goinfra/pull/942
- https://github.com/openshift-kni/eco-gotests/pull/490
- https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2844

ci: prevent forks from running crons

---

Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2899

Update Go to v1.24.2

---

.github/workflows/preflight.yml

Similar to: https://github.com/redhat-best-practices-for-k8s/certsuite-sample-workload/pull/553

Fix preflight

---

.github/workflows/pre-main.yml
.github/workflows/preflight.yml
.github/workflows/recreate-image.yml
.github/workflows/scorecard.yml

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2927

Runner update to ubuntu-24.04

---

Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2962

Update Go to v1.24.3

---

Dockerfile
Dockerfile.local
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/3002

Update Go to v1.24.4
